// NoSQL: MongoDB
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by user_id

Table posts {
  id uuid [primary key]
  user_id uuid
  title varchar
  text text [note: 'Content of the post']
  location_id uuid
  created_at timestamp
  attachment_urls array
  comment_ids array  // de-normalizing for quick access to comments and reactions
}

table attachments {
  id uuid [primary key]
  user_id uuid
  post_id uuid
  url varchar
  size int
  created_at timestamp
}

Ref: attachments.post_id > posts.id