// NoSQL: MongoDB
// Replication:
// - master-slave (async)
// - replication factor 3
//
// Sharding:
// - key based by id

Table users {
  id uuid [primary key]
  username varchar
  created_at timestamp
}