openapi: 3.0.0

tags:
  - name: Users
  - name: Posts
  - name: Reactions
  - name: Comments

info:
  title: Social network for travelers API
  description: Current API describes interaction with Social network
  version: 1.0.0

paths:
  /posts:
    get:
      summary: Get posts
      description: Method gets feed of posts for the authenticated user
      tags:
        - Posts
      parameters:
        - name: location
          in: query
          description: The location that relates to posts for filtering
          required: false
          schema:
            $ref: '#/components/schemas/Location'
        - name: userId
          in: query
          description: The user id for filtering posts by authority
          required: false
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        400:
          description: Bad Request
        500:
          description: Server error
    post:
      summary: Create post
      description: Method creates post for user
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: id of the post
        400:
          description: Bad Request
        500:
          description: Server error
  /posts/{id}:
    get:
      summary: Get specific post
      description: Method gets single post for the authenticated user
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
    put:
      summary: Update post
      description: Method updates post for user
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        422:
          description: Validation exception
        500:
          description: Server error
    delete:
      summary: Delete post
      description: Method deletes post
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
  /locations:
    get:
      summary: Get locations for traveling
      description: Method gets the list of popular posts
      tags:
        - Posts
      parameters:
        - name: target
          in: query
          description: The location for searching the most popular locations around
          required: true
          schema:
            $ref: '#/components/schemas/Location'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error

  /posts/{postId}/reactions:
    get:
      summary: Get the list of post reactions
      description: Method gets the list of reactions for the authenticated user for specific post
      tags:
        - Reactions
      parameters:
        - name: postId
          in: path
          description: ID of the post that needs to be marked with reaction
          required: true
          schema:
            type: string
            format: uuid
        - name: reactionType
          in: query
          description: The reaction type for filtering
          required: false
          schema:
            type: number
            format: int64
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reaction'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
    post:
      summary: Create reaction
      description: Method creates reaction to post
      tags:
        - Reactions
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reaction'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: id of the reaction
        400:
          description: Bad Request
        422:
          description: Validation exception
        500:
          description: Server error
  /reactions/{id}:
    get:
      summary: Get specific reaction
      description: Method gets single reaction for the authenticated user
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          description: ID of the reaction
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reaction'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
    delete:
      summary: Delete reaction
      description: Method deletes reaction
      tags:
        - Reactions
      parameters:
        - name: id
          in: path
          description: ID of the reaction
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /posts/{postId}/comments:
    post:
      summary: Create comment
      description: Method creates comment
      tags:
        - Comments
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: id of the comment
        400:
          description: Bad Request
        422:
          description: Validation exception
        500:
          description: Server error
    get:
      summary: Get the list of post comments
      description: Method gets the list of comments for the authenticated user for specific post
      tags:
        - Comments
      parameters:
        - name: postId
          in: path
          description: ID of the post
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
  /comment/{id}:
    get:
      summary: Get specific comment
      description: Method gets single comment for the authenticated user
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          description: ID of the comment that needs to be fetched
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
    put:
      summary: Update comment
      description: Method updates comment
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          description: ID of the comment
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        422:
          description: Validation exception
        500:
          description: Server error
    delete:
      summary: Delete comment
      description: Method deletes comment
      tags:
        - Comments
      parameters:
        - name: id
          in: path
          description: ID of the comment
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /users/{userId}:
    get:
      summary: Get user info
      description: Method gets the user information
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server error
  /users/{userId}/subscriptions:
    post:
      summary: Subscribe to user
      description: Method creates subscription to user
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
    delete:
      summary: Unsubscribe to user
      description: Method deletes subscription to user
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "id of the user"
        about:
          type: string
          description: "Information about the user"
        name:
          type: string
          description: "User name"
        email:
          type: string
          format: email
    Post:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "id of the post"
        userId:
          type: string
          description: "id of the post author"
          format: uuid
        text:
          type: string
          description: "The content of the post"
          example: "The text of the post related to Red Square at Moscow"
        location:
          $ref: '#/components/schemas/Location'
        images:
          type: array
          description: "The images associated with the post"
          items:
            type: string
            description: "Base64 encoded image binary body"
            example: "base64encodedimagebody"
      required:
        - id
        - userId
        - text
        - location
        - images
    Reaction:
      type: object
      properties:
        id:
          type: string
          description: id of the reaction
          format: uuid
        userId:
          type: string
          description: id of the reaction author
          format: uuid
        postId:
          type: string
          description: id of the post
          format: uuid
        reactionType:
          type: number
          description: The reaction type represented as integer number
          format: int64
          example: 123
        createdAt:
          type: string
          format: date-string
          description: The date the reaction has been created at
      required:
        - id
        - userId
        - postId
        - reactionType
        - createdAt
    Comment:
      type: object
      properties:
        id:
          type: string
          description: id of the comment
          format: uuid
        userId:
          type: string
          description: id of the comment author
          format: uuid
        postId:
          type: string
          description: id of the post
          format: uuid
        text:
          type: string
          description: The string text of the comment
          example: "This is great"
        createdAt:
          type: string
          format: date-string
          description: The date the reaction has been created at
        images:
          type: array
          description: The images associated with the post
          items:
            type: string
            description: Base64 encoded image binary body
            example: "base64encodedimagebody"
      required:
        - id
        - userId
        - postId
        - text
        - createdAt
        - images
    Location:
      type: array
      description: The location of the place associated with this post
      items:
        type: number
        format: double
        description: The coordinate
      example: [55.753544, 37.621202]